# OpenCode Sandbox Container for Phixr - Lightweight Development Version
FROM python:3.11-slim

# Install essential tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Create directories
RUN mkdir -p /phixr-context /phixr-results /workspace

# Configure git
RUN git config --global user.email "phixr-bot@localhost" && \
    git config --global user.name "Phixr Bot" && \
    git config --global init.defaultBranch main

# Create opencode mock script
RUN mkdir -p /usr/local/bin && cat > /usr/local/bin/opencode << 'SCRIPT_EOF'
#!/bin/bash
set -e

echo "Phixr Mock OpenCode v0.1.0"

# Load context
if [ -f /phixr-context/issue.json ]; then
  echo "Context loaded"
fi

# Clone repo if provided
if [ -n "$PHIXR_REPO_URL" ]; then
  cd /workspace
  git clone --depth 1 "$PHIXR_REPO_URL" repo 2>&1 || true
  cd repo || exit 1
  
  if [ -n "$PHIXR_BRANCH" ]; then
    git checkout "$PHIXR_BRANCH" 2>/dev/null || git checkout -b "$PHIXR_BRANCH"
  fi
fi

# Simulate work
if [ -d /workspace/repo ]; then
  cd /workspace/repo
  
  # Create or modify a file
  if [ ! -f README_AI.md ]; then
    cat > README_AI.md << 'EOF'
# Generated by Phixr AI

This file was created by the Phixr AI agent.

```python
def generated_function():
    return "Hello from Phixr AI!"
```

Timestamp: $(date)
EOF
  fi
  
  # Git operations
  git add -A 2>/dev/null || true
  if ! git diff --cached --quiet; then
    git commit -m "Phixr AI: Code generation" 2>/dev/null || true
  fi
  
  # Capture results
  git diff HEAD~1 > /phixr-results/changes.diff 2>/dev/null || git diff > /phixr-results/changes.diff 2>/dev/null || true
  git status --porcelain > /phixr-results/status.txt 2>/dev/null || true
  git log --oneline -5 > /phixr-results/log.txt 2>/dev/null || true
fi

echo 0 > /phixr-results/exit_code.txt
echo "$(date -Iseconds)" > /phixr-results/completed_at.txt
echo "OpenCode session completed"
exit 0
SCRIPT_EOF

RUN chmod +x /usr/local/bin/opencode

WORKDIR /workspace
ENV OPENCODE_MODE=build OPENCODE_TELEMETRY=0

ENTRYPOINT ["bash", "-c"]
CMD ["opencode"]

LABEL org.opencontainers.image.title="Phixr OpenCode Mock" \
      org.opencontainers.image.version="0.1.0-dev"
